version: "3.9"
services:
  api:
    build: ./API
    container_name: api
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    ports:
      - "4000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_DATABASE: biblioteca
    volumes:
      - mysql_db:/var/lib/mysql
      - ./DB/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  mysql_db: