apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-hpa
  namespace: so1p2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50