apiVersion: v1
kind: Service
metadata:
  name: grpc-client-svc
  namespace: so1p2
spec:
  selector:
    app: grpc-app
  ports:
    - name: grpc-client-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort