apiVersion: v1
kind: Service
metadata:
  name: node-svc
  namespace: so1p2
spec:
  selector:
    app: node-app
  ports:
    - name: node-port
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer