apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  selector:
    app: python-app
  ports:
    - name: python-port
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort