apiVersion: v1
kind: Service
metadata:
  name: python-svc
  namespace: so1p2
spec:
  selector:
    app: python-app
  ports:
    - name: python-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort