apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: so1p2
type: Opaque
data:
  DB_PORT : 'MzMwNg==' 
  DB_HOST : 'bG9jYWxob3N0' 
  DB_USER : 'cm9vdA==' 
  DB_PASSWORD : 'cm9vdA==' 
  DB_DATABASE : 'Y29udHJvbE5vdGFz' 