version: "3.9"
services:
  api:
    image: daniel499/monitor_api:1.0.0
    container_name: api_monitor
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DATABASE=history
      - DB_PORT=3306
      - API_PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: history
    volumes:
      - mysql_db:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql

  front:
    image: daniel499/monitor_client:2.0.0
    container_name: client
    environment:
      - VITE_API_URL=35.211.62.154:4000
    ports:
      - "80:5000"

volumes:
  mysql_db: