apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-app
  namespace: so1p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-app
  template:
    metadata:
      labels:
        app: grpc-app
    spec:
      containers:
      - name: grpc-server
        image: daniel499/grpc_server:1.0.0
        resources:
          requests:
            cpu: "400m"
        ports:
        - containerPort: 3001
        env:
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_PORT
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_DATABASE
      - name: grpc-client
        image: daniel499/grpc_client:1.0.0
        resources:
          requests:
            cpu: "400m"
        ports:
        - containerPort: 3000