apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: so1p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2.1-alpine
        resources:
          requests:
            cpu: "400m"
        ports:
        - containerPort: 6379